Using NumPy 
Python object types :Tuple, List, String, Arrays, Dictionary, Data Frames


In [1]:
import numpy as np

In [2]:
###   Numpy is imported as a library

In [3]:
my_list = [1,2,3]
my_list
type(my_list)

list

In [4]:
my_tuple=(1,2,3)
my_tuple

(1, 2, 3)

In [5]:
my_array1=np.array(my_list)
my_array2=np.array([1,2,3])
print(my_array1)
print(my_array2)

[1 2 3]
[1 2 3]


In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **There are many Built-in Methods:**
np.arange, np.zeros, np.ones, np.eye

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(2)

array([0.29288871, 0.79078221])

In [18]:
np.random.rand(5,5)

array([[0.71507746, 0.10631194, 0.77970651, 0.629349  , 0.54881727],
       [0.11111961, 0.74740828, 0.50939885, 0.53834447, 0.83320796],
       [0.3037328 , 0.58626594, 0.67617252, 0.85215106, 0.12826153],
       [0.1937226 , 0.5294135 , 0.81874207, 0.03395418, 0.28167226],
       [0.17177174, 0.12557907, 0.49613929, 0.08054126, 0.87626727]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [19]:
#np.random.seed(5)
np.random.randn(2)

array([-1.4532556 ,  1.30154343])

In [20]:
np.random.randn(5,5)

array([[-1.25673187,  0.10563709,  0.06579882,  2.27514692,  0.42505561],
       [ 1.50806316, -0.5084681 , -0.13987453, -0.6185591 ,  1.22278462],
       [-0.21575132,  0.15640017,  0.09542133,  0.31832012, -0.75916407],
       [ 0.45341609, -0.70977983,  0.77924453,  0.5697734 ,  0.53969016],
       [ 2.72061949,  0.99091395, -0.2332476 ,  0.66807703,  0.48097613]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [21]:
np.random.randint(1,100)

43

In [22]:
np.random.randint(1,100,10)

array([79, 86, 40, 85, 79, 65, 64, 55, 17,  4])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [26]:
ranarr

array([39, 23, 27, 10, 35, 23,  3, 47,  3, 11])

In [27]:
ranarr.max()

47

In [28]:
ranarr.argmax()

7

In [29]:
ranarr.min()

3

In [30]:
ranarr.argmin()

6

## Shape

Shape is an attribute that arrays have (not a method):

In [31]:
# Vector
arr.shape

(25,)

In [32]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25).shape

(1, 25)

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25,1).shape

(25, 1)

Array Operations:
np.dot, np.vstack, np.hstack, Indexing Slicing, 